microsoft/vscode-azureapicenter

package-lock.json
package.json

https://github.com/microsoft/vscode-azureapicenter/issues/124

fix: search should not show in command palette and update version

---

.github/workflows/cd.yml

https://github.com/microsoft/vscode-azureapicenter/actions/runs/8683853037

build: update cd pipeline to target branch

---

src/commands/generateHttpFile.ts

feat: generate variables for parameters in header, query string and path

---

NOTICE.txt
package-lock.json
package.json
src/commands/generateHttpFile.ts

feat: generate HTTP body using json-schema-faker

---

src/commands/searchApi.ts
src/uiStrings.ts

refactor: search hint placeholder

---

.github/workflows/cd.yml
.github/workflows/publish.yml

runs on  https://github.com/microsoft/vscode-azureapicenter/actions/runs/8813643723
relative task:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27692290
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27692291

ci: support release prerelease version

---

src/commands/setApiRuleset.ts
src/constants.ts
src/uiStrings.ts

feat: add default rule for API lint

---

.github/workflows/publish.yml

https://github.com/microsoft/vscode-azureapicenter/issues/145

fix: fix publish tag logic

---

codecov.yml

format the codecov report
instead of

test: code cov settings

---

.github/workflows/e2e.yml
package.json

This reverts commit d4c6d46f7b981aa53bab91c9be893bf4d14a91c5.

fix: Revert "test: matrix platform (#159)"

---

.gitignore
package-lock.json
package.json
package.nls.json
src/commands/detectBreakingChange.ts
src/commands/generateHttpFile.ts
src/commands/generateMarkdownDocument.ts
src/constants.ts
src/extension.ts
src/uiStrings.ts
src/utils/apiSpecificationUtils.ts
src/utils/fsUtil.ts
src/utils/openApiUtils.ts
webpack.config.js

feat: generate Markdown from OpenAPI spec

---

src/test/unit/tree/azureAccountTreeItem.test.ts
src/tree/AzureAccountTreeItem.ts
src/uiStrings.ts

fix: show select subs when select empty subs

---

README.md

ci: add badge to readme

---

src/extension.ts
src/utils/telemetryUtils.ts

https://github.com/microsoft/vscode-azuretools/blob/02c16b920e7970fc14b76d30044021c22908e82a/utils/src/tree/AzExtTreeItem.ts#L154
the ext pkg direct throw error when no sub

fix: do not send sub data when no sub selected

---

package.json
package.nls.json
src/constants.ts
src/extension.ts
src/test/unit/tree/dataPlaneAccountTreeItem.test.ts
src/tree/DataPlaneAccount.ts
src/uiStrings.ts

feat: add wiki guide for API Catalog

---

src/commands/generateApiLibrary.ts
src/commands/generateHttpFile.ts
src/commands/rules/openRule.ts
src/commands/setApiRuleset.ts
src/commands/testInPostman.ts
src/constants.ts
src/extension.ts
src/test/unit/commands/setApiRuleset.test.ts
src/uiStrings.ts
src/utils/ensureExtension.ts
src/utils/ruleUtils.ts

feat: add 'None' option to unselect active style guide

---

.github/workflows/cli.yml

refactor: add email notification

---

.github/workflows/cd.yml

fix: https://github.com/microsoft/vscode-azureapicenter/actions/runs/12300141155

ci: update cd for tag

---

.vscode/extensions.json
.vscode/tasks.json
evalprompt/README.md
evalprompt/genSpecFromPrompt/promptfooconfig.yaml
evalprompt/genSpecFromPrompt/spectral.mjs
evalprompt/genSpecFromPrompt/vars.csv

Dynamically list all directories under evalprompt.

ci: prompt test tasks

---

src/uiStrings.ts

docs: update string to fix issue 324

---

package.json
package.nls.json
src/commands/generateApiSpecFromCodeProject.ts
src/extension.ts
src/prompts/generateApiSpecFromCodeProject.ts
src/test/unit/commands/generateApiSpecFromCodeProject.test.ts

Command Palette:
‘Copilot’ context menu:
Demo video:
[[Chat Mode + #codebase] Generate OpenAPI spec from whole code project](https://microsoftapc-my.sharepoint.com/:v:/g/personal/junhan_microsoft_com1/EXEJHm5jQmNAk6nsPmb6j0IBLzWP8WWDwfNaerrnjleH5Q?e=HuFBfI&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D)

feat: generate OpenAPI spec from whole code project

---

package.json
package.nls.json
src/extension.ts
src/uiStrings.ts

docs: rebrand name to api center portal

---

package.nls.json

feat: rename api center portal to api center portal view

---

package.json
package.nls.json
src/azure/ApiCenter/contracts.ts
src/commands/copyDeploymentUrl.ts
src/extension.ts
src/test/unit/commands/copyDeploymentUrl.test.ts
src/tree/ApiDeploymentTreeItem.ts
src/uiStrings.ts

Demo: https://microsoftapc-my.sharepoint.com/:v:/g/personal/junhan_microsoft_com1/EWFwcJXCW9RPvd41eJfR_uoBxEPtdJ7MiySnpJfGydj78A?e=jkQyDX&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D

feat: copy Runtime URL of Deployment

---

src/tree/DataPlaneAccount.ts

https://github.com/microsoft/vscode-azureapicenter/issues/344

fix: fix command for learn from api center portal guide

---

src/commands/addDataPlaneApis.ts
src/commands/handleUri.ts
src/test/unit/commands/addDataPlaneApi.test.ts
src/test/unit/commands/handleUri.test.ts
src/test/unit/commands/removeDataplaneApi.test.ts
src/test/unit/tree/dataPlaneAccountTreeItem.test.ts
src/tree/DataPlaneAccount.ts
src/uiStrings.ts

perf: show child item when add data plane apis

---

src/azure/azureLogin/dataSessionProvider.ts

https://github.com/microsoft/vscode-azureapicenter/issues/359

fix: data plane permission scope change

---

src/commands/exportApi.ts
src/test/unit/utils/generalUtils.test.ts
src/utils/generalUtils.ts

https://github.com/microsoft/vscode-azureapicenter/issues/371

fix: update the spec file type according to the export api

---

package.json

fix: use our own submenu as we cannot contribute to copilot menu now
